[project]
name = "compiler-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jlucasbx", email = "jlucasb16@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
compiler-test = "compiler_test:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
